development:
  adapter: postgresql
  encoding: unicode
  database: blog_dev
  pool: 5
  host: localhost
  username: u

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  host: localhost
  username: u

production:
  adapter: postgresql
  encoding: unicode
  database: blog_production
  pool: 5
  username: u